// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['cms']['CMS']['AddProject'](arg1);
}

export function CreateInitialConfig(arg1) {
  return window['go']['cms']['CMS']['CreateInitialConfig'](arg1);
}

export function EditProject(arg1, arg2, arg3) {
  return window['go']['cms']['CMS']['EditProject'](arg1, arg2, arg3);
}

export function ListProjects() {
  return window['go']['cms']['CMS']['ListProjects']();
}

export function LoadConfig(arg1) {
  return window['go']['cms']['CMS']['LoadConfig'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['cms']['CMS']['RemoveProject'](arg1);
}
