// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddProject(arg1:model.Project):Promise<void>;

export function CreateInitialConfig(arg1:string):Promise<void>;

export function EditProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListProjects():Promise<Array<model.Project>>;

export function LoadConfig(arg1:string):Promise<model.Config>;

export function RemoveProject(arg1:string):Promise<void>;
