// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableRepos() {
  return window['go']['auth']['Binding']['GetAvailableRepos']();
}

export function GetUser() {
  return window['go']['auth']['Binding']['GetUser']();
}

export function HandleCallback(arg1, arg2) {
  return window['go']['auth']['Binding']['HandleCallback'](arg1, arg2);
}

export function IsAuthed() {
  return window['go']['auth']['Binding']['IsAuthed']();
}

export function Logout() {
  return window['go']['auth']['Binding']['Logout']();
}

export function RestoreLastSession() {
  return window['go']['auth']['Binding']['RestoreLastSession']();
}

export function StartOAuthLogin() {
  return window['go']['auth']['Binding']['StartOAuthLogin']();
}
