// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRawToken(arg1) {
  return window['go']['auth']['Binding']['GetRawToken'](arg1);
}

export function GetState() {
  return window['go']['auth']['Binding']['GetState']();
}

export function GetToken(arg1) {
  return window['go']['auth']['Binding']['GetToken'](arg1);
}

export function GetUserDetails(arg1) {
  return window['go']['auth']['Binding']['GetUserDetails'](arg1);
}

export function HandleCallback(arg1, arg2) {
  return window['go']['auth']['Binding']['HandleCallback'](arg1, arg2);
}

export function StartOAuthLogin() {
  return window['go']['auth']['Binding']['StartOAuthLogin']();
}
