// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function GetAvailableRepos():Promise<Array<string>>;

export function GetUser():Promise<auth.UserDetails>;

export function HandleCallback(arg1:string,arg2:string):Promise<string>;

export function IsAuthed():Promise<boolean>;

export function Logout():Promise<void>;

export function RestoreLastSession():Promise<void>;

export function StartOAuthLogin():Promise<string>;
