// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function GetRawToken(arg1:string):Promise<string>;

export function GetState():Promise<string>;

export function GetToken(arg1:string):Promise<string>;

export function GetUserDetails(arg1:string):Promise<auth.UserDetails>;

export function HandleCallback(arg1:string,arg2:string):Promise<string>;

export function StartOAuthLogin():Promise<string>;
