// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['Auth']['GetState']();
}

export function GetToken(arg1) {
  return window['go']['main']['Auth']['GetToken'](arg1);
}

export function HandleCallback(arg1, arg2) {
  return window['go']['main']['Auth']['HandleCallback'](arg1, arg2);
}

export function StartOAuthLogin() {
  return window['go']['main']['Auth']['StartOAuthLogin']();
}
