// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState():Promise<string>;

export function GetToken(arg1:string):Promise<string>;

export function HandleCallback(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function StartOAuthLogin():Promise<string>;
